In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

%matplotlib inline

In [12]:
digits=load_digits()

In [39]:
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [40]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9648148148148148

In [41]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [42]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975925925925926

In [44]:
from sklearn.model_selection import KFold
kf =KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [45]:
for train_index,test_index in kf.split([1,2,3,4,5,4,6,5,5,7,8,9,10]):
    print(train_index,type(train_index))

[ 5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
[ 0  1  2  3  4  9 10 11 12] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>


In [46]:
kf.split([1,2,3,4,5,4,6,5,5,7,8,9,10])

<generator object _BaseKFold.split at 0x000002770F50B6C8>

In [47]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [49]:
from sklearn.model_selection import StratifiedKFold

In [51]:
folds =StratifiedKFold(n_splits=3)

In [66]:
l_scores=[]
rf_scores=[]
svm_scores=[]
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    l_scores.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    svm_scores.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    rf_scores.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

In [67]:
l_scores

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [68]:
svm_scores

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [69]:
rf_scores

[0.9248747913188647, 0.9515859766277128, 0.9315525876460768]

In [70]:
from sklearn.model_selection import cross_val_score

In [72]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [73]:
cross_val_score(SVC(),digits.data,digits.target,cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [74]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=5)

array([0.925     , 0.90555556, 0.95543175, 0.96100279, 0.91922006])